services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${APP_CONFIG__POSTGRES__NAME}
      POSTGRES_USER: ${APP_CONFIG__POSTGRES__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__POSTGRES__PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge